---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-rakshitgondwal-online-v1alpha1-scaler
  failurePolicy: Fail
  name: vscaler.kb.io
  rules:
  - apiGroups:
    - api.rakshitgondwal.online
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scalers
  sideEffects: None
