# permissions for end users to view scalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scaler-operator
    app.kubernetes.io/part-of: scaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-viewer-role
rules:
- apiGroups:
  - api.rakshitgondwal.online
  resources:
  - scalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.rakshitgondwal.online
  resources:
  - scalers/status
  verbs:
  - get
